### ISSUE TITLE
FE: Side bar menu

### ISSUE THREAD

**Issue by swathisridharan** [OpenXeggo/Invoice-fi#18]
Create the sidebar menu items as shown in the design here:
https://www.figma.com/file/kUx5TaiJwMlTRsorabDk5i/Invoice-App?node-id=148%3A799

Make sure the different menus also have associated routing links redirecting to specific pages as needed

**NOTE:**
Make sure you are creating a single component for the sidebar menu individual item which can just be duplicated instead of creating multiple different components for each item.

**Comment by Mihde9** [comment]
Issue has been fixed.
