### ISSUE TITLE
FE: Dashboard to be redesigned

### ISSUE THREAD

**Issue by swathisridharan** [OpenXeggo/Invoice-fi#19]
These are the specific components to be designed for this particular ticket, please don't cover any other components as these are being done by other Devs.
https://www.figma.com/file/kUx5TaiJwMlTRsorabDk5i/Invoice-App?node-id=148%3A799

1.  Xeggo Logo on top left corner
2. Welcome line on top - "Hello There...to get started"
3. Cards structure for Overview, Recent Transactions, Notifications with the pictures given on initial screen
4. The metrics tiles section that say "Client", "Invoice" under Overview...
5. "Connect Wallet" button to be displayed on top right if wallet is not connected
6. "Create Invoice" button to be displayed on top right if wallet is connected

**NOTE:**
Make sure you are creating a single component for each category which can just be duplicated instead of creating multiple different components for each.
For example:
- The cards are all the same. So create one card and duplicate it to just have different data inside for each
- The metrics tiles are all the same. So create one tile and duplicate it to just have different data inside of each
- "Connect Wallet" button occurs across multiple screens, so create one button that can be reused across the app

**Comment by aman-webdev** [comment]
Merged but needs some ui fixes. To be done after we add some data through moralis

**Comment by Mihde9** [comment]
Issue has been fixed.
