### ISSUE TITLE
Notification card

### ISSUE THREAD

**Issue by Mihde9** [OpenXeggo/Invoice-fi#60]
The notification card needs to be worked on and made as seen in the design

**Comment by jaythebeez** [comment]
Can you add a screenshot of this?

**Comment by Mihde9** [comment]
![Screenshot (368)](https://user-images.githubusercontent.com/61977000/186174035-328033da-882b-48b3-ab05-7aeb348850c2.png)

**Comment by Mihde9** [comment]
Issue has been worked on.
