### ISSUE TITLE
Align to the top

### ISSUE THREAD

**Issue by Mihde9** [OpenXeggo/Invoice-fi#61]
Welcome back, Create invoice should be aligned to the top with the HOME button on the sidebar

**Comment by aman-webdev** [comment]
@Mihde9 share reference ss of both outputs. I dont understand this

**Comment by Mihde9** [comment]
![Screenshot (372)](https://user-images.githubusercontent.com/61977000/186278565-e3990385-50a9-4411-b344-3ff06c49d5dc.jpg)
This is how it looks like.. its not aligned to the top

**Comment by Mihde9** [comment]
![Screenshot (373)](https://user-images.githubusercontent.com/61977000/186278774-39c9ec45-cd8e-464e-99f4-4d5a109c1a2e.png)
This is how it should be aligned

**Comment by jaythebeez** [comment]
I have worked on this issue it's included in my pr

**Comment by Mihde9** [comment]
Alright

**Comment by aman-webdev** [comment]
This has been fixed in the pr

**Comment by Mihde9** [comment]
Issue has been fixed.
