### ISSUE TITLE
Side bar Icon misalignment

### ISSUE THREAD

**Issue by Mihde9** [OpenXeggo/Invoice-fi#63]

**Comment by jaythebeez** [comment]
Please share screenshot of what you mean and properly explain

**Comment by Mihde9** [comment]
![Screenshot (370)](https://user-images.githubusercontent.com/61977000/186175264-a91a0c39-e0ec-4185-9475-8b0394252ee5.jpg)

Kindly compare this to the figma design

**Comment by Mihde9** [comment]
Issue has been fixed.
